local_costmap/inflation_layer/inflation_radius: 0.19
DWAPlannerROS:
  # acceleration limits
  acc_lim_x: 2.5  # 2.5
  acc_lim_th: 3.2  # 3.2
  
  # velocity limits
  max_vel_x: 1.0  # 0.55
  min_vel_x: 0.0  # 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.75
  min_rot_vel: 0.2

  # goal tolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

  # dwa parameters
  vx_samples: 6
  vy_samples: 1
  vth_samples: 42
  controller_frequency: 10

  # scoring parameters
  occdist_scale: 0.008
  path_distance_scale: 0.98
  goal_distance_scale: 0.94
  
