scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 180
    neighbors: 3
    window: 1
- name: nan_to_inf_filter
  type: segbot_sensors/NanToInfFilter
- name: footprint_filter
  type: segbot_sensors/SegbotFootprintFilter
  params:
    footprint_frame: base_footprint
    footprint: [0.385,0.3,0.385,-0.3,-0.35,-0.25,-0.35,0.25]

