sudo: required
dist: bionic
language: generic
compiler:
  - gcc
env:
  global:
    - CATKIN_CONFIG='--no-install'  # work around kinova-ros install bug
    - CCACHE_DIR=$HOME/.ccache
    - ROS_DISTRO="melodic"
    - ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - UPSTREAM_WORKSPACE=file
  matrix:
    - BUILD_PKGS_WHITELIST="only_segbot_base"
#    - BUILD_PKGS_WHITELIST="only_segbot_arm"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
