<?xml version="1.0"?>

<root
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="gazebo_segbot_base_link_surface">
    <gazebo reference="base_link">
      <mu1 value="1.0" />
      <mu2 value="1.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_castor_wheel_link_surface">
    <gazebo reference="caster_wheel_link">
      <mu1 value="1.0" />
      <mu2 value="1.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_wheel_surface" params="parent suffix">
    <gazebo reference="${parent}_${suffix}_wheel_link" >
      <mu1 value="1.0" />
      <mu2 value="1.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>
  </xacro:macro>

  <xacro:macro name="segbot_base_link_inertial" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <inertial>
        <mass value="30" />
        <origin xyz="-0.1 0 -0.075" />
        <inertia ixx="3.0" ixy="0.0" ixz="0.0"
          iyy="3.0" iyz="0.0"
          izz="2.0" />
      </inertial>
    </xacro:if>
    <xacro:unless value="$(arg use_full_gazebo_model)">
      <inertial>
        <mass value="30" />
        <origin xyz="0 0 -0.2165" />
        <inertia ixx="3000.0" ixy="0.0" ixz="0.0"
          iyy="3000.0" iyz="0.0"
          izz="30.0" />
      </inertial>
    </xacro:unless>
  </xacro:macro>

  <xacro:macro name="segbot_base_link_collision" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-base-link.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
    <xacro:unless value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 -0.05" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.305" length="0.3330" />
        </geometry>
      </collision>
    </xacro:unless>
  </xacro:macro>

  <xacro:macro name="gazebo_laser_obstacle">
    <xacro:unless value="$(arg use_full_gazebo_model)">
      <joint name="laser_obstacle_joint" type="fixed">
        <origin xyz="0.0 0 0.3165" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="laser_obstacle" />
      </joint>

      <link name="laser_obstacle">
        <inertial>
          <mass value="0.1" />
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
                   iyy="0.01"  iyz="0.0"
                   izz="0.01" />
        </inertial>
       <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.001 0.001 0.001" />
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.25 0.6 0.4" />
          </geometry>
        </collision>
      </link>
    </xacro:unless>
  </xacro:macro>

  <xacro:macro name="segbot_castor_support_link_collision" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-castor-link.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="segbot_castor_wheel_link_collision" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-castor-wheel.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="segbot_wheel_collision" params="suffix">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-${suffix}-wheel.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="segbot_battery_box_collision">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 ${5.5*INCH_TO_M}" rpy="0 0 0"/>
        <geometry>
          <box size="${7*INCH_TO_M} ${14*INCH_TO_M} ${11*INCH_TO_M}" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="laptop_collision">
    <!-- <xacro:if value="$(arg use_full_gazebo_model)"> -->
      <collision>
        <origin xyz="0 0 ${0.375*INCH_TO_M}" rpy="0 0 0"/>
        <geometry>
          <box size="${12*INCH_TO_M} ${14*INCH_TO_M} ${0.75*INCH_TO_M}" />
        </geometry>
      </collision>
    <!-- </xacro:if> -->
  </xacro:macro>

  <xacro:macro name="laptop_screen_collision">
    <!-- <xacro:if value="$(arg use_full_gazebo_model)"> -->
      <collision>
        <origin xyz="${6*INCH_TO_M} 0 -${0.375*INCH_TO_M}" rpy="0 0 0"/>
        <geometry>
          <box size="${12*INCH_TO_M} ${14*INCH_TO_M} ${0.75*INCH_TO_M}" />
        </geometry>
      </collision>
    <!-- </xacro:if> -->
  </xacro:macro>

  <xacro:macro name="aluminium_sheet_collision" params="thickness length width">
    <!-- <xacro:if value="$(arg use_full_gazebo_model)"> -->
      <collision>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thickness}" />
        </geometry>
      </collision>
    <!-- </xacro:if> -->
  </xacro:macro>

  <xacro:macro name="beam_8020_collision" params="length">
    <!-- <xacro:if value="$(arg use_full_gazebo_model)"> -->
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${1*INCH_TO_M} ${1*INCH_TO_M} ${length}" />
        </geometry>
      </collision>
    <!-- </xacro:if> -->
  </xacro:macro>

  <xacro:macro name="standoff_collision" params="radius length">
    <!-- <xacro:if value="$(arg use_full_gazebo_model)"> -->
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}" />
        </geometry>
      </collision>
    <!-- </xacro:if> -->
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_ros_controllers">
    <gazebo>
      <xacro:if value="$(arg use_full_gazebo_model)">
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
          <updateRate>100</updateRate>
          <leftJoint>base_link_right_wheel_joint</leftJoint>
          <rightJoint>base_link_left_wheel_joint</rightJoint>
          <wheelSeparation>0.5380</wheelSeparation>
          <wheelDiameter>0.2410</wheelDiameter>
          <torque>20</torque>
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
      </xacro:if>
      <xacro:unless value="$(arg use_full_gazebo_model)">
        <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>base_footprint</robotBaseFrame>
          <odometryRate>100</odometryRate>
        </plugin>
      </xacro:unless>
    </gazebo>
  </xacro:macro>

</root>

