<?xml version="1.0"?>

<root
  xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="gazebo_segbot_base_link_surface">
    <gazebo reference="base_link">
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_castor_wheel_link_surface">
    <gazebo reference="caster_wheel_link">
      <mu1 value="10.0" />
      <mu2 value="10.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_wheel_surface" params="parent suffix">
    <gazebo reference="${parent}_${suffix}_wheel_link" >
      <mu1 value="10.0" />
      <mu2 value="10.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>
  </xacro:macro>

  <xacro:macro name="segbot_base_link_inertial" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <inertial>
        <mass value="30" />
        <origin xyz="-0.1 0 -0.075" />
        <inertia ixx="3.0" ixy="0.0" ixz="0.0"
          iyy="3.0" iyz="0.0" 
          izz="2.0" />
      </inertial>
    </xacro:if>
    <xacro:unless value="$(arg use_full_gazebo_model)">
      <inertial>
        <mass value="30" />
        <origin xyz="0 0 -0.2165" />
        <inertia ixx="300.0" ixy="0.0" ixz="0.0"
          iyy="300.0" iyz="0.0" 
          izz="300.0" />
      </inertial>
    </xacro:unless>
  </xacro:macro>

  <xacro:macro name="segbot_base_link_collision" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-base-link.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
    <xacro:unless value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="-0.15 0 0.1" rpy="0 0 0" />
        <geometry>
          <box size="0.5 0.4 0.6330" />
        </geometry>
      </collision>
    </xacro:unless>
  </xacro:macro>

  <xacro:macro name="segbot_castor_support_link_collision" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-castor-link.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="segbot_castor_wheel_link_collision" >
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-castor-wheel.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="segbot_wheel_collision" params="suffix">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://segbot_description/meshes/rmp50-${suffix}-wheel.dae" scale="0.0254 0.0254 0.0254"/>
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="segbot_battery_box_collision">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 ${5.5*INCH_TO_M}" rpy="0 0 0"/>
        <geometry>
          <box size="${7*INCH_TO_M} ${14*INCH_TO_M} ${11*INCH_TO_M}" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="laptop_collision">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 ${0.375*INCH_TO_M}" rpy="0 0 0"/>
        <geometry>
          <box size="${12*INCH_TO_M} ${14*INCH_TO_M} ${0.75*INCH_TO_M}" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="laptop_screen_collision">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="${6*INCH_TO_M} 0 -${0.375*INCH_TO_M}" rpy="0 0 0"/>
        <geometry>
          <box size="${12*INCH_TO_M} ${14*INCH_TO_M} ${0.75*INCH_TO_M}" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="aluminium_sheet_collision" params="thickness length width">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thickness}" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="beam_8020_collision" params="length">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${1*INCH_TO_M} ${1*INCH_TO_M} ${length}" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="standoff_632_collision" params="length">
    <xacro:if value="$(arg use_full_gazebo_model)">
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="0.003175" />
        </geometry>
      </collision>
    </xacro:if>
  </xacro:macro>

  <xacro:macro name="gazebo_segbot_ros_controllers">
    <gazebo>
      <xacro:if value="$(arg use_full_gazebo_model)">
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
          <updateRate>100</updateRate>
          <leftJoint>base_link_right_wheel_joint</leftJoint>
          <rightJoint>base_link_left_wheel_joint</rightJoint>
          <wheelSeparation>0.5380</wheelSeparation>
          <wheelDiameter>0.2410</wheelDiameter>
          <torque>20</torque>
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
      </xacro:if>
      <xacro:unless value="$(arg use_full_gazebo_model)">
        <plugin name="object_controller" filename="libgazebo_ros_planar_move.so">
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <odometryFrame>odom</odometryFrame>
          <robotBaseFrame>base_footprint</robotBaseFrame>
          <odometryRate>100</odometryRate>
        </plugin>
      </xacro:unless>
    </gazebo>
  </xacro:macro>

</root>

