<?xml version="1.0"?>
<root xmlns:xacro="http://ros.org/wiki/xacro">
 
  <xacro:macro name="aluminium_sheet" params="name parent thickness length width *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}_link"/>
      <child link="${name}_link"/>
    </joint>
    <link name="${name}_link">
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
                 iyy="0.01"  iyz="0.0"
                 izz="0.01" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${thickness}" />
        </geometry>
        <material name="dark_grey" />
      </visual>
      <xacro:aluminium_sheet_collision thickness="${thickness}" length="${length}" width="${width}"/>
    </link>

    <gazebo reference="${name}_link">
      <material>Gazebo/Grey</material>
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp value="1000000.0" />
      <kd value="1.0" />
    </gazebo>

  </xacro:macro>

</root>

