EBandPlannerROS:

  # TRAJECTORY CONTROL
  differential_drive: true

  # velocity limits
  max_vel_lin: 1.0
  max_vel_th: 0.5
  min_vel_lin: 0.4
  min_in_place_vel_th: 0.25

  # goal tolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2

  # angular velocity PID
  k_prop: 0.75

  #eband parameters
  eband_internal_force_gain: 3.0
  #eband_external_force_gain: 1.0

  costmap_weight: 15.0
