footprint: [[0.265, 0.285], [0.265, -0.285], [-0.265, -0.285], [-0.38, 0], [-0.265, 0.285]]
#robot_radius: 0.30
planner_frequency: 1.0

recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'rotate_recovery'
    type: 'rotate_backaway_recovery/RotateBackawayRecovery'

conservative_reset:
  reset_distance: 3.0
  layer_names: ['obstacle_layer']

aggressive_reset:
  reset_distance: 0.0
  layer_names: ['obstacle_layer']

