<?xml version="1.0"?>

<robot name="segbot_bu" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find segbot_description)/urdf/segway_110_base.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/vbu/common.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/vbu/segbot_chassis.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/mounts/sick_tim_mount.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/gazebo/segbot.gazebo.xacro" />
  
  <xacro:property name="SENSOR_BEAM_LENGTH" value="10.75" /> <!-- inches -->
    
  <xacro:include filename="$(find ur_description)/urdf/inc/ur5e_macro.xacro"/>
  <xacro:ur5e_robot prefix="" />

  <joint name="arm_joint" type="fixed">
    <parent link="laptop_base_plate_link" />
    <child link = "ur5e_base_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${M_PI / 2.0}" />
  </joint>

  <xacro:include filename="$(find robotiq_2f_140_gripper_visualization)/urdf/robotiq_arg2f_140_model.xacro" />
  <joint name="gripper_joint" type="fixed">
    <parent link="tool0" />
    <child link = "robotiq_arg2f_base_link" />
    <origin xyz="0.0 0.0 0.01" rpy="0.0 0.0 ${pi/2}" />
  </joint>

  <!-- Add the segbot base -->
  <xacro:segway_robot />

  <xacro:segbot_chassis parent="base_chassis">
    <origin xyz="${BASE_PLATE_X_OFFSET*INCH_TO_M} 0 ${BASE_PLATE_Z_OFFSET*INCH_TO_M}" rpy="0 0 ${M_PI}"/>
  </xacro:segbot_chassis>

  <!-- Add the forward facing sick_tim  for navigation -->
  <xacro:sick_tim_mount name="sick_tim" parent="base_chassis" ros_topic="sick_tim/scan">
    <!-- <origin xyz="${0.125*INCH_TO_M} 0 0" rpy="0 0 0" /> -->
    <origin xyz="${12.75*INCH_TO_M} 0 ${2.25*INCH_TO_M}" rpy="0 0 0"/>
  </xacro:sick_tim_mount>



  <gazebo>
    <!-- <plugin name="object_controller" filename="libgazebo_ros_planar_move.so"> -->
    <!--   <commandTopic>cmd_vel</commandTopic> -->
    <!--   <odometryTopic>odom</odometryTopic> -->
    <!--   <odometryFrame>odom</odometryFrame> -->
    <!--   <robotBaseFrame>base_footprint</robotBaseFrame> -->
    <!--   <odometryRate>100</odometryRate> -->
    <!-- </plugin> -->
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>100</updateRate>
      <leftJoint>left_wheel</leftJoint>
      <rightJoint>right_wheel</rightJoint>
      <wheelSeparation>0.479111</wheelSeparation>
      <wheelDiameter>0.46228</wheelDiameter>
      <wheelTorque>13</wheelTorque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
  </gazebo>

</robot>
