<?xml version="1.0"?>

<root xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find segbot_description)/urdf/components/aluminium_sheet.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/components/battery_box.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/components/beam_8020.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/components/laptop.urdf.xacro" />
  <xacro:include filename="$(find segbot_description)/urdf/components/standoff.urdf.xacro" />

  <xacro:macro name="segbot_chassis_parametrized" params="parent *origin front_vertical_beam_length back_vertical_beam_length laptop_plate_length laptop_plate_width">

    <!-- base plate -->
    <xacro:aluminium_sheet name="chassis_base_plate" parent="${parent}"
                           thickness="${0.25*INCH_TO_M}" length="${16*INCH_TO_M}" width="${14*INCH_TO_M}">
      <xacro:insert_block name="origin" />
    </xacro:aluminium_sheet>

    <!-- left side aluminium angle (only the vertical portion for convenience -->
    <xacro:aluminium_sheet name="chassis_left_plate" parent="chassis_base_plate"
                           thickness="${0.25*INCH_TO_M}" length="${16*INCH_TO_M}" width="${4*INCH_TO_M}">
      <origin xyz="0 ${6.75*INCH_TO_M} -${2*INCH_TO_M}" rpy="-${M_PI/2} 0 0" />
    </xacro:aluminium_sheet>
    <!-- right side aluminium angle (only the vertical portion for convenience -->
    <xacro:aluminium_sheet name="chassis_right_plate" parent="chassis_base_plate"
                           thickness="${0.25*INCH_TO_M}" length="${16*INCH_TO_M}" width="${4*INCH_TO_M}">
      <origin xyz="0 -${6.75*INCH_TO_M} -${2*INCH_TO_M}" rpy="+${M_PI/2} 0 0" />
    </xacro:aluminium_sheet>

    <!-- battery box -->
    <xacro:battery_box name="battery_box" parent="chassis_base_plate">
      <origin xyz="-${2.0*INCH_TO_M} 0 ${0.25*INCH_TO_M}" rpy="0 0 0" />
    </xacro:battery_box>

    <!-- 80/20 base beams -->
    <!-- front beam -->
    <xacro:beam_8020 name="front_base_beam" parent="chassis_base_plate" length="${12*INCH_TO_M}">
      <origin xyz="${4.5*INCH_TO_M} ${6*INCH_TO_M} ${0.75*INCH_TO_M}"
        rpy="${M_PI/2} 0 0" />
    </xacro:beam_8020>
    <!-- back beam -->
    <xacro:beam_8020 name="back_base_beam" parent="chassis_base_plate" length="${12*INCH_TO_M}">
      <origin xyz="-${6.5*INCH_TO_M} ${6*INCH_TO_M} ${0.75*INCH_TO_M}"
        rpy="${M_PI/2} 0 0" />
    </xacro:beam_8020>

    <!-- 80/20 vertical beams -->
    <xacro:beam_8020 name="back_left_vertical_beam" parent="back_base_beam" length="${back_vertical_beam_length}">
      <origin xyz="0 0 ${0.5*INCH_TO_M}"
        rpy="-${M_PI/2} 0 0" />
    </xacro:beam_8020>
    <xacro:beam_8020 name="front_left_vertical_beam" parent="front_base_beam" length="${front_vertical_beam_length}">
      <origin xyz="0 0 ${0.5*INCH_TO_M}"
        rpy="-${M_PI/2} 0 0" />
    </xacro:beam_8020>
    <xacro:beam_8020 name="back_right_vertical_beam" parent="back_base_beam" length="${back_vertical_beam_length}">
      <origin xyz="0 0 ${11.5*INCH_TO_M}"
        rpy="-${M_PI/2} 0 0" />
    </xacro:beam_8020>
    <xacro:beam_8020 name="front_right_vertical_beam" parent="front_base_beam" length="${front_vertical_beam_length}">
      <origin xyz="0 0 ${11.5*INCH_TO_M}"
        rpy="-${M_PI/2} 0 0" />
    </xacro:beam_8020>

    <!-- 80/20 laptop support beam -->
    <!-- left laptop support beam (from the back beam) -->
    <xacro:beam_8020 name="left_laptop_support_beam" parent="back_left_vertical_beam" length="${12*INCH_TO_M}">
      <origin xyz="-${0.5*INCH_TO_M} ${1*INCH_TO_M} ${back_vertical_beam_length - 0.5*INCH_TO_M}"
        rpy="${M_PI} -${M_PI/2} 0" />
    </xacro:beam_8020>
    <xacro:beam_8020 name="right_laptop_support_beam" parent="back_right_vertical_beam" length="${12*INCH_TO_M}">
      <origin xyz="-${0.5*INCH_TO_M} -${1*INCH_TO_M} ${back_vertical_beam_length - 0.5*INCH_TO_M}"
        rpy="${M_PI} -${M_PI/2} 0" />
    </xacro:beam_8020>

    <!-- laptop base plate -->
    <!-- from the left laptop support beam -->
    <xacro:aluminium_sheet name="laptop_base_plate" parent="left_laptop_support_beam" thickness="${0.125*INCH_TO_M}" length="${laptop_plate_length}" width="${laptop_plate_width}">
      <origin xyz="${0.5*INCH_TO_M} ${6.5*INCH_TO_M} ${6*INCH_TO_M}"
        rpy="${M_PI} -${M_PI/2} 0" />
    </xacro:aluminium_sheet>

    <!-- laptop -->
    <xacro:laptop name="laptop" parent="laptop_base_plate"> 
      <origin xyz="-${7.1*INCH_TO_M} 0 ${0.125*INCH_TO_M}" rpy="0 0 0" />
    </xacro:laptop>

  </xacro:macro>

  <xacro:macro name="segbot_chassis" params="parent *origin">
    <xacro:segbot_chassis_parametrized parent="${parent}" front_vertical_beam_length="${36*INCH_TO_M}"
      back_vertical_beam_length="${24*INCH_TO_M}" laptop_plate_length="${12*INCH_TO_M}"
      laptop_plate_width="${14*INCH_TO_M}">
      <xacro:insert_block name="origin" />
    </xacro:segbot_chassis_parametrized>
  </xacro:macro>

  <xacro:macro name="segbot_chassis_arm" params="parent *origin">
    <xacro:segbot_chassis_parametrized parent="${parent}" front_vertical_beam_length="${18*INCH_TO_M}"
      back_vertical_beam_length="${18*INCH_TO_M}" laptop_plate_length="${16*INCH_TO_M}"
      laptop_plate_width="${18*INCH_TO_M}">
      <xacro:insert_block name="origin" />
    </xacro:segbot_chassis_parametrized>
  </xacro:macro>

</root>
